[2024-10-01T18:49:02.126+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: intialization_database.create_football_airflow_connection manual__2024-10-01T18:43:09.008276+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
