[2024-10-09T11:54:19.756+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-09T11:54:19.809+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-09T11:54:12.562074+00:00 [queued]>
[2024-10-09T11:54:19.834+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-09T11:54:12.562074+00:00 [queued]>
[2024-10-09T11:54:19.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-09T11:54:19.861+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2024-10-09 11:54:12.562074+00:00
[2024-10-09T11:54:19.878+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=683) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-09T11:54:19.881+0000] {standard_task_runner.py:63} INFO - Started process 685 to run task
[2024-10-09T11:54:19.883+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'test_postgres_connection', 'manual__2024-10-09T11:54:12.562074+00:00', '--job-id', '3861', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmpj27hsg0b']
[2024-10-09T11:54:19.885+0000] {standard_task_runner.py:91} INFO - Job 3861: Subtask test_postgres_connection
[2024-10-09T11:54:20.047+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.test_postgres_connection manual__2024-10-09T11:54:12.562074+00:00 [running]> on host 512b8b1d19ac
[2024-10-09T11:54:20.251+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T11:54:12.562074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T11:54:12.562074+00:00'
[2024-10-09T11:54:20.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-09T11:54:20.332+0000] {logging_mixin.py:188} INFO - Connection to PostgreSQL DB successful
[2024-10-09T11:54:20.690+0000] {logging_mixin.py:188} INFO - Data exported to /opt/***/dags/csvs/date_csv/last_date.csv successfully.
[2024-10-09T11:54:20.700+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-09T11:54:20.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-09T11:54:20.861+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=test_postgres_connection, run_id=manual__2024-10-09T11:54:12.562074+00:00, execution_date=20241009T115412, start_date=20241009T115419, end_date=20241009T115420
[2024-10-09T11:54:20.960+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-09T11:54:21.120+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-09T11:54:21.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
